# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yossi/proj/email/plasmoid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yossi/proj/email/plasmoid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yossi/proj/email/plasmoid/CMakeFiles /home/yossi/proj/email/plasmoid/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yossi/proj/email/plasmoid/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named plasma_applet_email_notifyer

# Build rule for target.
plasma_applet_email_notifyer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plasma_applet_email_notifyer
.PHONY : plasma_applet_email_notifyer

# fast build rule for target.
plasma_applet_email_notifyer/fast:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/build
.PHONY : plasma_applet_email_notifyer/fast

#=============================================================================
# Target rules for targets named plasma_applet_email_notifyer_automoc

# Build rule for target.
plasma_applet_email_notifyer_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plasma_applet_email_notifyer_automoc
.PHONY : plasma_applet_email_notifyer_automoc

# fast build rule for target.
plasma_applet_email_notifyer_automoc/fast:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer_automoc.dir/build.make CMakeFiles/plasma_applet_email_notifyer_automoc.dir/build
.PHONY : plasma_applet_email_notifyer_automoc/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

# target to build an object file
common/Imap.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Imap.o
.PHONY : common/Imap.o

# target to preprocess a source file
common/Imap.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Imap.i
.PHONY : common/Imap.i

# target to generate assembly for a file
common/Imap.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Imap.s
.PHONY : common/Imap.s

# target to build an object file
common/Pop3.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Pop3.o
.PHONY : common/Pop3.o

# target to preprocess a source file
common/Pop3.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Pop3.i
.PHONY : common/Pop3.i

# target to generate assembly for a file
common/Pop3.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Pop3.s
.PHONY : common/Pop3.s

# target to build an object file
common/Socket.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Socket.o
.PHONY : common/Socket.o

# target to preprocess a source file
common/Socket.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Socket.i
.PHONY : common/Socket.i

# target to generate assembly for a file
common/Socket.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/Socket.s
.PHONY : common/Socket.s

# target to build an object file
common/config.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/config.o
.PHONY : common/config.o

# target to preprocess a source file
common/config.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/config.i
.PHONY : common/config.i

# target to generate assembly for a file
common/config.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/config.s
.PHONY : common/config.s

# target to build an object file
common/configUi.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/configUi.o
.PHONY : common/configUi.o

# target to preprocess a source file
common/configUi.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/configUi.i
.PHONY : common/configUi.i

# target to generate assembly for a file
common/configUi.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/configUi.s
.PHONY : common/configUi.s

# target to build an object file
common/emailAccount.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailAccount.o
.PHONY : common/emailAccount.o

# target to preprocess a source file
common/emailAccount.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailAccount.i
.PHONY : common/emailAccount.i

# target to generate assembly for a file
common/emailAccount.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailAccount.s
.PHONY : common/emailAccount.s

# target to build an object file
common/emailChecker.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailChecker.o
.PHONY : common/emailChecker.o

# target to preprocess a source file
common/emailChecker.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailChecker.i
.PHONY : common/emailChecker.i

# target to generate assembly for a file
common/emailChecker.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailChecker.s
.PHONY : common/emailChecker.s

# target to build an object file
common/emailNotifyer.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyer.o
.PHONY : common/emailNotifyer.o

# target to preprocess a source file
common/emailNotifyer.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyer.i
.PHONY : common/emailNotifyer.i

# target to generate assembly for a file
common/emailNotifyer.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyer.s
.PHONY : common/emailNotifyer.s

# target to build an object file
common/emailNotifyerUi.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyerUi.o
.PHONY : common/emailNotifyerUi.o

# target to preprocess a source file
common/emailNotifyerUi.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyerUi.i
.PHONY : common/emailNotifyerUi.i

# target to generate assembly for a file
common/emailNotifyerUi.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/emailNotifyerUi.s
.PHONY : common/emailNotifyerUi.s

# target to build an object file
common/error.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/error.o
.PHONY : common/error.o

# target to preprocess a source file
common/error.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/error.i
.PHONY : common/error.i

# target to generate assembly for a file
common/error.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/common/error.s
.PHONY : common/error.s

# target to build an object file
plasma-email-notifyer.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma-email-notifyer.o
.PHONY : plasma-email-notifyer.o

# target to preprocess a source file
plasma-email-notifyer.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma-email-notifyer.i
.PHONY : plasma-email-notifyer.i

# target to generate assembly for a file
plasma-email-notifyer.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma-email-notifyer.s
.PHONY : plasma-email-notifyer.s

# target to build an object file
plasma_applet_email_notifyer_automoc.o:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma_applet_email_notifyer_automoc.o
.PHONY : plasma_applet_email_notifyer_automoc.o

# target to preprocess a source file
plasma_applet_email_notifyer_automoc.i:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma_applet_email_notifyer_automoc.i
.PHONY : plasma_applet_email_notifyer_automoc.i

# target to generate assembly for a file
plasma_applet_email_notifyer_automoc.s:
	$(MAKE) -f CMakeFiles/plasma_applet_email_notifyer.dir/build.make CMakeFiles/plasma_applet_email_notifyer.dir/plasma_applet_email_notifyer_automoc.s
.PHONY : plasma_applet_email_notifyer_automoc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... plasma_applet_email_notifyer"
	@echo "... plasma_applet_email_notifyer_automoc"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... common/Imap.o"
	@echo "... common/Imap.i"
	@echo "... common/Imap.s"
	@echo "... common/Pop3.o"
	@echo "... common/Pop3.i"
	@echo "... common/Pop3.s"
	@echo "... common/Socket.o"
	@echo "... common/Socket.i"
	@echo "... common/Socket.s"
	@echo "... common/config.o"
	@echo "... common/config.i"
	@echo "... common/config.s"
	@echo "... common/configUi.o"
	@echo "... common/configUi.i"
	@echo "... common/configUi.s"
	@echo "... common/emailAccount.o"
	@echo "... common/emailAccount.i"
	@echo "... common/emailAccount.s"
	@echo "... common/emailChecker.o"
	@echo "... common/emailChecker.i"
	@echo "... common/emailChecker.s"
	@echo "... common/emailNotifyer.o"
	@echo "... common/emailNotifyer.i"
	@echo "... common/emailNotifyer.s"
	@echo "... common/emailNotifyerUi.o"
	@echo "... common/emailNotifyerUi.i"
	@echo "... common/emailNotifyerUi.s"
	@echo "... common/error.o"
	@echo "... common/error.i"
	@echo "... common/error.s"
	@echo "... plasma-email-notifyer.o"
	@echo "... plasma-email-notifyer.i"
	@echo "... plasma-email-notifyer.s"
	@echo "... plasma_applet_email_notifyer_automoc.o"
	@echo "... plasma_applet_email_notifyer_automoc.i"
	@echo "... plasma_applet_email_notifyer_automoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

